In [7]:
# Install PyTorch if it's not already available in this environment
# (Jupyter magic installs into the notebook's Python environment)
%pip install -q torch

import torch
import numpy as np

Note: you may need to restart the kernel to use updated packages.


 Creating Tensors from Lists
The simplest way: create a tensor from a Python list!

In [8]:
import torch

# Create a tensor from a list
try:
    t1 = torch.tensor([1, 2, 3, 4, 5])
except NameError:
    t1 = torch.tensor([1, 2, 3, 4, 5])
print("1D tensor:")
print(t1)
print(f"Shape: {t1.shape}")
print(f"Size: {t1.size()}")
print()

# Create a 2D tensor (matrix)
t2 = torch.tensor([[1, 2, 3], 
                   [4, 5, 6]])
print("2D tensor (matrix):")
print(t2)
print(f"Shape: {t2.shape}")
print()

# Create a 3D tensor
t3 = torch.tensor([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("3D tensor:")
print(t3)
print(f"Shape: {t3.shape}")
print(f"Number of dimensions: {t3.dim()}")

1D tensor:
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Size: torch.Size([5])

2D tensor (matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Number of dimensions: 3
