In [1]:
import torch

In [2]:
# Create two matrices
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B:")
print(B)
print(f"Shape: {B.shape}")
print()

# Matrix multiplication using @
result = A @ B
print("A @ B (matrix multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# Using torch.matmul()
result2 = torch.matmul(A, B)
print("torch.matmul(A, B):")
print(result2)
print("(Same result!)")

Matrix A:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])
Shape: torch.Size([2, 2])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])
Shape: torch.Size([2, 2])

torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])
(Same result!)


In [4]:
# Matrix-vector multiplication
M = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

v = torch.tensor([5, 6], dtype=torch.float32)

print("Matrix M:")
print(M)
print(f"Shape: {M.shape}")
print()

print("Vector v:")
print(v)
print(f"Shape: {v.shape}")
print()

# Matrix × Vector
result = M @ v
print("M @ v (matrix-vector multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# How it works
print("How it works:")
print(f"Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = {M[0, 0]}*{v[0]} + {M[0, 1]}*{v[1]} = {result[0]}")
print(f"Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = {M[1, 0]}*{v[0]} + {M[1, 1]}*{v[1]} = {result[1]}")

Matrix M:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Vector v:
tensor([5., 6.])
Shape: torch.Size([2])

M @ v (matrix-vector multiplication):
tensor([17., 39.])
Shape: torch.Size([2])

How it works:
Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = 1.0*5.0 + 2.0*6.0 = 17.0
Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = 3.0*5.0 + 4.0*6.0 = 39.0


In [5]:
# Batch matrix multiplication
# Create batch of matrices: (batch_size, rows, cols)
batch_A = torch.randn(3, 2, 4)  # 3 matrices, each 2×4
batch_B = torch.randn(3, 4, 3)  # 3 matrices, each 4×3

print("Batch A (3 matrices, each 2×4):")
print(batch_A)
print(f"Shape: {batch_A.shape}")
print()

print("Batch B (3 matrices, each 4×3):")
print(batch_B)
print(f"Shape: {batch_B.shape}")
print()

# Batch matrix multiplication
batch_result = torch.bmm(batch_A, batch_B)
print("Batch matrix multiplication result:")
print(batch_result)
print(f"Shape: {batch_result.shape}")
print("(3 matrices, each 2×3)")
print()

# Verify: first matrix multiplication
A0 = batch_A[0]
B0 = batch_B[0]
result0 = A0 @ B0

print("First matrix multiplication (manual):")
print(result0)
print()

print("First matrix multiplication (from batch):")
print(batch_result[0])
print("(Should match!)")
print(f"Are they equal? {torch.allclose(result0, batch_result[0])}")

Batch A (3 matrices, each 2×4):
tensor([[[ 1.9429,  0.1368,  0.1403, -0.2015],
         [-0.0141, -0.2092, -0.2375, -0.1432]],

        [[ 1.8528, -1.6297,  0.1302,  1.4440],
         [-1.1006, -1.4318, -1.8133,  0.7655]],

        [[-0.0043,  0.7066, -0.9736,  0.2487],
         [-1.2217, -1.8474, -1.0509,  1.0041]]])
Shape: torch.Size([3, 2, 4])

Batch B (3 matrices, each 4×3):
tensor([[[ 0.1954, -0.6030,  0.7495],
         [-1.0695,  0.2626,  0.5463],
         [ 0.0299,  1.2228, -0.1012],
         [-0.0658, -0.4530, -0.5811]],

        [[-0.7664,  0.8552,  0.6946],
         [-0.1572, -0.1384,  0.4607],
         [ 0.0665, -0.8042, -0.5350],
         [-1.0868,  0.1845, -0.1106]],

        [[-0.3011, -1.0926, -0.4364],
         [ 0.3832, -0.1734,  1.2494],
         [-0.1067,  0.5068, -1.4042],
         [-0.9606, -0.2236, -0.1952]]])
Shape: torch.Size([3, 4, 3])

Batch matrix multiplication result:
tensor([[[ 0.2508, -0.8727,  1.6339],
         [ 0.2233, -0.2720, -0.0176]],

        [[-2

In [6]:
# Element-wise multiplication (different from matrix multiplication!)
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

# Element-wise multiplication
element_wise = A * B
print("A * B (element-wise multiplication):")
print(element_wise)
print()

# Matrix multiplication (for comparison)
matrix_mult = A @ B
print("A @ B (matrix multiplication):")
print(matrix_mult)
print()

print("Notice: Element-wise (*) is different from matrix multiplication (@)!")
print(f"Element-wise: {A[0, 0]} * {B[0, 0]} = {element_wise[0, 0]}")
print(f"Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = {matrix_mult[0, 0]}")

Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

A * B (element-wise multiplication):
tensor([[ 5., 12.],
        [21., 32.]])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])

Notice: Element-wise (*) is different from matrix multiplication (@)!
Element-wise: 1.0 * 5.0 = 5.0
Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = 19.0
