In [1]:
import torch


In [2]:
# Create a 2D tensor
A = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.float32)

print("Original tensor A:")
print(A)
print(f"Shape: {A.shape}")
print()

# Transpose using .T
A_transpose = A.T
print("A.T (transpose):")
print(A_transpose)
print(f"Shape: {A_transpose.shape}")
print()

# Using .t() (only for 2D tensors)
A_transpose2 = A.t()
print("A.t() (transpose, 2D only):")
print(A_transpose2)
print(f"Shape: {A_transpose2.shape}")
print()

print("How it works:")
print(f"A[0, 1] = {A[0, 1]} becomes A.T[1, 0] = {A_transpose[1, 0]}")
print(f"A[1, 0] = {A[1, 0]} becomes A.T[0, 1] = {A_transpose[0, 1]}")

Original tensor A:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])

A.T (transpose):
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Shape: torch.Size([3, 2])

A.t() (transpose, 2D only):
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Shape: torch.Size([3, 2])

How it works:
A[0, 1] = 2.0 becomes A.T[1, 0] = 2.0
A[1, 0] = 4.0 becomes A.T[0, 1] = 4.0


In [3]:
# Create a 3D tensor
t = torch.tensor([[[1, 2], 
                   [3, 4]], 
                  [[5, 6], 
                   [7, 8]]], dtype=torch.float32)

print("Original 3D tensor:")
print(t)
print(f"Shape: {t.shape}")
print()

# Transpose specific dimensions
# transpose(dim0, dim1) swaps dim0 and dim1
t_transposed = torch.transpose(t, 0, 2)
print("Transposed (swapped dimension 0 and 2):")
print(t_transposed)
print(f"Shape: {t_transposed.shape}")
print()

# Using permute() to rearrange all dimensions
t_permuted = t.permute(2, 1, 0)
print("Permuted (rearranged dimensions):")
print(t_permuted)
print(f"Shape: {t_permuted.shape}")
print()

print("Original shape: (2, 2, 2)")
print("After permute(2, 1, 0): (2, 2, 2) - last dimension becomes first")

Original 3D tensor:
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
Shape: torch.Size([2, 2, 2])

Transposed (swapped dimension 0 and 2):
tensor([[[1., 5.],
         [3., 7.]],

        [[2., 6.],
         [4., 8.]]])
Shape: torch.Size([2, 2, 2])

Permuted (rearranged dimensions):
tensor([[[1., 5.],
         [3., 7.]],

        [[2., 6.],
         [4., 8.]]])
Shape: torch.Size([2, 2, 2])

Original shape: (2, 2, 2)
After permute(2, 1, 0): (2, 2, 2) - last dimension becomes first


In [4]:
# Example: Matrix transpose for multiplication
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

# (A @ B).T = B.T @ A.T (property of transpose)
AB = A @ B
AB_transpose = AB.T

BTA = B.T @ A.T

print("(A @ B).T:")
print(AB_transpose)
print()

print("B.T @ A.T:")
print(BTA)
print()

print("Are they equal? (Should be!)")
print(torch.allclose(AB_transpose, BTA))
print()

# Transpose of transpose = original
print("Transpose of transpose:")
print("(A.T).T:")
print(A.T.T)
print()
print("Original A:")
print(A)
print(f"Are they equal? {torch.equal(A.T.T, A)}")


Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

(A @ B).T:
tensor([[19., 43.],
        [22., 50.]])

B.T @ A.T:
tensor([[19., 43.],
        [22., 50.]])

Are they equal? (Should be!)
True

Transpose of transpose:
(A.T).T:
tensor([[1., 2.],
        [3., 4.]])

Original A:
tensor([[1., 2.],
        [3., 4.]])
Are they equal? True
